# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'drawing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'RealmSwift'
  # Pods for firebase-app-tutorial
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

	pod 'Firebase/Auth'
	pod 'Firebase/Analytics'
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
	pod 'ProgressHUD'
	pod 'JGProgressHUD'
	pod 'SDWebImage'
end
